name: fleet_watcher_mobile
description: "A new Flutter project"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.1.0
  animated_snack_bar: ^0.4.0
  calendar_date_picker2: ^0.5.3
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/onboarding/
    - assets/logos/
    - assets/splash_screen/