import 'package:fleet_watcher_mobile/models/boitier.dart';

List<Boitier> generateFakeBoitiers() {
  return [
    Boitier(
      'AB123CD',
      '123 Rue de Exemple, Paris hcfvdci jhgdzsv jgqzufcv qgclygac hjzgcugxj ystcyug lzytdyxgl dzadyx',
      'Jean Dupont',
      '80 km/h',
      '15L',
      1,
      false,
    ),
    Boitier(
      'EF456GH',
      '456 Avenue Test, Lyon',
      'Marie Curie',
      '65 km/h',
      '10L',
      2,
      true,
    ),
    Boitier(
      'IJ789KL',
      '789 Boulevard Imaginaire, Marseille',
      'Pierre Dupuis',
      '90 km/h',
      '40L',
      3,
      true,
    ),
    Boitier(
      'MN012OP',
      '012 Route de Fiction, Toulouse',
      'Sophie Martin',
      '70 km/h',
      '35L',
      4,
      false,
    ),
    Boitier('QR345ST', '345 Passage de Test, Bordeaux', 'Paul Leblanc',
        '85 km/h', '18L', 5, true),
    Boitier('ST678UV', '678 Rue de la Création, Lille', 'Alice Lefevre',
        '100 km/h', '35L', 6, false),
    Boitier(
      'WX901YZ',
      '901 Route du Test, Nantes',
      'Marc Dubois',
      '75 km/h',
      '24L',
      7,
      false,
    ),
    Boitier('AB234CD', '234 Avenue des Champs, Strasbourg', 'Claire Simon',
        '85 km/h', '15L', 8, false),
    Boitier('EF567GH', '567 Boulevard du Réel, Rennes', 'Lucas Moreau',
        '95 km/h', '21L', 9, false),
    Boitier('IJ890KL', '890 Passage de l\'Innovation, Montpellier',
        'Nina Renault', '60 km/h', '18L', 10, true),
    Boitier('MN123OP', '123 Boulevard du Futur, Clermont-Ferrand',
        'David Martin', '70 km/h', '26L', 11, true),
    Boitier('QR456ST', '456 Rue du Développement, Amiens', 'Julie Lefevre',
        '80 km/h', '20L', 12, false),
    Boitier('ST789UV', '789 Route des Étoiles, Tours', 'Pierre Germain',
        '90 km/h', '16L', 13, true),
    Boitier('WX012YZ', '012 Avenue de l\'Horizon, Perpignan', 'Sophie Leroy',
        '85 km/h', '21L', 14, false),
    Boitier('AB345CD', '345 Passage de la Lumière, Reims', 'Julien Morin',
        '95 km/h', '17L', 15, true),
  ];
}
